# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a93a634bcf240ddcec669fc42fd8ad0"
name = "discount-magnet"
handle = "discount-magnet"
application_url = "https://intensive-culture-thumbzilla-cisco.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-for-customer-account-test.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_price_rules,read_products,write_discounts,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://intensive-culture-thumbzilla-cisco.trycloudflare.com/auth/callback",
  "https://intensive-culture-thumbzilla-cisco.trycloudflare.com/auth/shopify/callback",
  "https://intensive-culture-thumbzilla-cisco.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
